Modules/Role/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>['auth','rbac'],'preifix'=>'role'],function() {
    Route::resource('role','RoleController');
    Route::post('role/delete','RoleController@delete')->name('role.delete');

});

Modules/Role/Entities/Permission.php
<?php

namespace Modules\Role\Entities;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    protected $fillable = [];
    protected $table ='permissions';
}

Modules/Role/Entities/Role.php
<?php

namespace Modules\Role\Entities;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = [];

    protected $table ="roles";
    
}

Modules/Role/Entities/RolePermission.php
<?php

namespace Modules\Role\Entities;

use Illuminate\Database\Eloquent\Model;

class RolePermission extends Model
{
    protected $fillable = [];
    protected $table ="role_permissions";
}

Modules/Role/Http/Controllers/RoleController.php
<?php

namespace Modules\Role\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Role\Entities\Permission;
use Modules\Role\Entities\Role;
use Modules\Role\Entities\RolePermission;

use Session;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $roles = Role::where('type', 'regular')->orderBy('name','ASC')->paginate(config('number_of_pages'));

        $permissions = Permission::groupby('module')->get();


        return view('role::admin.index',
            compact('roles', 'permissions')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('role::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {

        $rules = [
            'name' => 'required|unique:roles',
            // 'permission_id' => 'required'
        ];

        $request->validate($rules);


        $role = new Role;

        $role->name = $request->name;

        $role->role_code = md5($role->name).''.date('ymdhis').''.rand(0,9999999);


        //created_by
        $user_id = auth()->user()->id;
        $role->save();


        if ($request->permission_id) {
            //assign the permission to created role
            foreach ($request->permission_id as $value) {

                $role_permission = new RolePermission;
                $role_permission->role_id = $role->id;
                $role_permission->permission_id = $value;

                $role_permission->save();
            }
        }




        // for additional settings

        // if ($request->settings) {

        //     $role_permission = new RolePermission;
        //     $role_permission->role_id = $role->id;
        //     $role_permission->permission_id = $request->settings;

        //     $role_permission->save();

        //     //for post settings
        //     $role_permission = new RolePermission;
        //     $role_permission->role_id = $role->id;
        //     $role_permission->permission_id = $request->post_settings;
        //     $role_permission->save();
        // }


        Session::flash('message', 'Role Created Successfully!');

        Session::flash('alert-class', 'alert-success');


        return back();
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('role::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $role = Role::where('role_code',$id)->first();


        $permissions = Permission::groupby('module')->get();

        $role_permission = RolePermission::where('role_id', $id)
            ->pluck('permission_id')
            ->all();

        return view('role::admin.edit',
            compact('role', 'permissions', 'role_permission')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        $role = Role::where('role_code',$id)->first();

        $id= $role->id;

        $rules = [
            'name' => 'required|unique:roles,name,'.$id,
            // 'type' =>'required'
        ];


        $request->validate($rules);



        //delete all previously assigned permission

        $role_permission = RolePermission::where('role_id', $id)->get();

        foreach ($role_permission as $value) {
            $value->delete();
        }


        $role->name = $request->name;
        $role->save();

        // now re-assign permission from the selected form
        if ($request->permission_id) {
            foreach ($request->permission_id as $value) {
                $role_permission = new RolePermission();
                $role_permission->role_id = $id;
                $role_permission->permission_id = $value;
                $role_permission->save();
            }
        }

        // for additional settings

        // if ($request->settings) {
        //     $role_permission = new RolePermission;
        //     $role_permission->role_id = $role->id;
        //     $role_permission->permission_id = $request->settings;

        //     $role_permission->save();

        //     //for post settings
        //     $role_permission = new RolePermission;
        //     $role_permission->role_id = $role->id;
        //     $role_permission->permission_id = $request->post_settings;
        //     $role_permission->save();
        // }


        Session::flash('message', 'Role Updated Successfully!');

        Session::flash('alert-class', 'alert-success');

        return redirect()->route('role.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }

    public function delete(Request $request)
    {


        if ($request->id) {
            $role = Role::whereIn('id', $request->id)->delete();
        }

        return back();
    }
}

Modules/Role/Resources/views/admin/edit.blade.php
@extends('layouts.admin.main')
@section('title')
    Edit Role
@endsection
@section('content')
<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Edit Role</h2>
                </div>            
            
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <ul class="nav nav-tabs">
                        <li class="nav-item"><a class="nav-link active show" data-toggle="tab" href="#addUser">Edit Role</a></li>        
                    </ul>
                    <div class="tab-content mt-0">
                       
                        <div class="tab-pane  active show" id="addUser">
                            <div class="body mt-2">

                               <form action="{{route('role.update',$role->role_code)}}" method="post">
                                @csrf
                                <input type="hidden" name="_method" value="put" />
                            
                                <div class="row clearfix">
                                    <div class="col-lg-6 col-md-6 col-sm-12">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">Role Name</span>
                                                </div>
                                                <input type="text" name="name" class="form-control show-tick @error('name') 
                                        is-invalid @enderror" placeholder="Role Name *" value="{{old('name',$role->name)}}" required="">
                                            </div>
                            
                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-6 col-sm-12">
                                    <hr>
                            
                                    Update Permissions
                                    <div class="table-responsive">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th>Add</th>
                                                    <th>View</th>
                                                    <th>Edit</th>
                                                    <th>Delete</th>
                                                </tr>
                            
                                            </thead>
                                            <tbody>
                            
                                                @foreach($permissions as $value)
                                                <tr>
                            
                                                    <th>
                                                        {{$value->module}}
                                                    </th>
                            
                                                    {{-- permissions --}}
                            
                                                    @php
                                                    $permission = Modules\Role\Entities\Permission::where('module',$value->module)->get();
                                                    @endphp
                            
                                                    @foreach ($permission as $v)
                                                    <td>
                                                        <label class="fancy-checkbox">
                                                            <input class="checkbox-tick" type="checkbox" name="permission_id[]" value="{{$v->id}}"
                                                                @if(in_array($v->id,$role_permission))
                                                            checked
                                                            @endif
                                                            >
                                                            <span></span>
                                                        </label>
                                                    </td>
                            
                                                    @endforeach
                            
                            
                            
                                                </tr>
                            
                            
                                                @endforeach
                            
                                            </tbody>
                                        </table>
                                    </div>
                            
                            
                                    {{-- <hr>
                                    Assign Other Permissions
                                    <hr>
                            
                                    <div class="table-responsive">
                                        <table class="table table-striped">
                                            <td>Company Profile</td>
                                            @php
                                            // dd($settings)
                                            @endphp
                                            @foreach($settings as $s)
                                            @if($s->link=='user/settings')
                                            <td>
                                                <label class="fancy-checkbox">
                            
                                                    <input class="checkbox-tick" type="checkbox" name="settings" value="{{$s->id}}"
                                                        @if(in_array($s->id,$role_permission))
                                                    checked
                                                    @endif
                                                    >
                                                    <span></span>
                            
                                                </label>
                            
                                                @endif
                                            </td>
                                          
                                            @if($loop->last)
                                            <input type="hidden" name="post_settings" value="{{ $s->id }}">
                                            @endif
                            
                                            @endforeach
                            
                                        </table>
                            
                            
                            
                                    </div> --}}
                            
                            
                                    <div class="col-12">
                                        <button type="submit" class="btn btn-primary">Update</button>
                            
                                        <a href="{{url('role/roles')}}" class="btn btn-secondary">
                                            CLOSE
                                        </a>
                                    </div>
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>            
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

Modules/Role/Resources/views/admin/index.blade.php
@extends('layouts.admin.main')
@section('title')
Roles
@endsection
@section('content')
<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Roles</h2>
                </div>
            </div>
        </div>
        <div class="row clearfix">

            <div class="col-lg-12">
                <div class="card">
                    <ul class="nav nav-tabs">
                        <li class="nav-item"><a class="nav-link @if(!session()->get('errors')) active show @endif"
                                data-toggle="tab" href="#Users">Roles</a></li>

                        @if(in_array('role.delete',session('permission')))

                        <li class="nav-item"><a class="nav-link @if(session()->get('errors')) active show @endif"
                                data-toggle="tab" href="#addUser">Add New Role</a></li>
                        @endif
                    </ul>
                    <div class="tab-content mt-0">
                        <div class="tab-pane @if(!session()->get('errors')) active show @endif" id="Users">
                                <!-- for search -->
                            @include('user::admin.search')
                            <div class="table-responsive">
                                <form method="post">
                                    @csrf
                                    {{-- check for delete permission --}}
                                    @if(in_array('role.delete',session('permission')))
                                    <button class="btn btn-danger"
                                        onclick="return confirm('Do you really want to delete this item?')"
                                        formaction="{{ route('role.delete') }}" type="submit">
                                        <i class="fa fa-trash"></i>
                                    </button>

                                    @endif
                                    <table class="table table-hover table-custom spacing8">
                                        <thead>
                                            <tr>
                                                @if(in_array('role.delete',session('permission')))

                                                    <th>
                                                        <label class="fancy-checkbox">
                                                            <input class="checkbox-tick" type="checkbox" id="check_all">
                                                            <span>#</span>
                                                        </label>
                                                    </th>
                                                @endif
                                                <th class="w60">Name</th>
                                                <th></th>
                                                <th></th>
                                                <th></th>

                                                <th>Created Date</th>

                                                @if(in_array('role.edit',session('permission')))

                                                <th class="w100">Action</th>

                                                @endif
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach ($roles as $value)
                                            <tr>
                                                @if(in_array('role.delete',session('permission')))

                                                    <td>

                                                        <label class="fancy-checkbox">
                                                            <input class="checkbox-tick checkitem" type="checkbox"
                                                                name="id[]" value="{{ $value->id }}">
                                                            <span></span>
                                                        </label>
                                                    </td>
                                                @endif
                                                <td>
                                                    <h6 class="mb-0">{{$value->name}}</h6>
                                                </td>

                                                <td></td>
                                                <td></td>
                                                <td></td>

                                                <td>

                                                    {{date('d M, Y',strtotime($value->created_at))}}

                                                </td>

                                                @if(in_array('role.edit',session('permission')))

                                                <td>


                                                    <a href="{{route('role.edit',$value->role_code)}}">
                                                        <i class="icon-pencil"></i>

                                                    </a>
                                                </td>

                                                @endif
                                            </tr>
                                            @endforeach

                                        </tbody>
                                    </table>
                                </form>

                                {!! $roles->render() !!}

                            </div>
                        </div>

                        @if(in_array('role.store',session('permission')))

                        <div class="tab-pane @if(session()->get('errors')) active show @endif" id="addUser">
                            <div class="body mt-2">
                                <form action="{{ route('role.store') }}" method="post">
                                    @csrf
                                    <div class="row clearfix">
                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text">Role Name</span>
                                                    </div>
                                                    <input type="text" name="name" class="form-control show-tick @error('name')
                                            is-invalid @enderror" placeholder="Role Name *" required=""
                                                        value="{{old('name')}}">


                                                    @error('name')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror
                                                </div>
                                            </div>


                                        </div>




                                        <div class="col-lg-12 col-md-6 col-sm-12" id="regular">
                                            <hr>
                                            Assign Module Permissions
                                            <div class="table-responsive">
                                                <table class="table table-striped">
                                                    <thead>
                                                        <tr>
                                                            <th></th>
                                                            <th>Add</th>
                                                            <th>View</th>
                                                            <th>Edit</th>
                                                            <th>Delete</th>
                                                        </tr>

                                                    </thead>
                                                    <tbody>

                                                        @foreach($permissions as $value)
                                                        <tr>

                                                            <th>
                                                                {{$value->module}}
                                                            </th>

                                                            {{-- permissions --}}

                                                            @php
                                                            $permission =
                                                            Modules\Role\Entities\Permission::where('module',$value->module)->get();
                                                            @endphp

                                                            @foreach ($permission as $v)
                                                            <td>
                                                                <label class="fancy-checkbox">
                                                                    <input class="checkbox-tick" type="checkbox"
                                                                        name="permission_id[]" value="{{$v->id}}">
                                                                    <span></span>
                                                                </label>
                                                            </td>

                                                            @endforeach



                                                        </tr>

                                                        @endforeach


                                                    </tbody>
                                                </table>
                                            </div>


                                            {{--

                                            <hr>
                                            Assign Other Permissions
                                            <hr>
                                                <div class="table-responsive">
                                                <table class="table table-striped">
                                                    <td>Company Profile</td>

                                                    @foreach($settings as $s)
                                                    @if($s->link=='user/settings')
                                                    <td>
                                                        <label class="fancy-checkbox">

                                                            <input class="checkbox-tick" type="checkbox" name="settings" value="{{$s->id}}">
                                            <span></span>
                                            </label>
                                            </td>
                                            @endif

                                            {{-- put post --}}
                                            {{-- @if($loop->last)
                                                    <input type="hidden" name="post_settings" value="{{ $s->id }}">
                                            @endif

                                            @endforeach

                                            </table>




                                        </div> --}}

                                    </div>


                                    <div class="col-12">
                                        <button type="submit" class="btn btn-primary">Add</button>
                                        <a href="{{route('role.index')}}" class="btn btn-secondary">
                                            CLOSE
                                        </a>
                                    </div>
                            </div>
                            </form>
                        </div>
                    </div>

                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
</div>



@endsection

Modules/Role/Resources/views/admin/search.blade.php
<form action="">
    <div class="row">
        <div class="col-md-6">
            <input type="text" placeholder="Search ..." class="form-control" name="keyword">

        </div>

    </div>
</form>