Modules/Category/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>['auth','rbac'],'prefix'=>'category'],function() {
    // Route::get('/categories', 'CategoryController@index');
    // Route::get('/create', 'CategoryController@create');
    // Route::post('/store', 'CategoryController@store');
    // Route::get('/edit/{id}', 'CategoryController@edit');
    // Route::post('/update', 'CategoryController@update');
    // Route::post('/destroy', 'CategoryController@destroy');


    Route::resource('category','CategoryController');

    Route::post('delete','CategoryController@delete')->name('category.delete');

    Route::get('search','CategoryController@search')->name('category.search');
});

Modules/Category/Entities/Category.php
<?php

namespace Modules\Category\Entities;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [];

    protected $table="categories";
}

Modules/Category/Http/Controllers/CategoryController.php
<?php

namespace Modules\Category\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;

use Illuminate\Http\Request;

use Illuminate\Routing\Controller;

use Modules\Category\Entities\Category;

use File;
use Modules\MainCategory\Entities\MainCategory;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $categories = Category::orderBy('id','DESC')
                    ->paginate(config('number_of_pages'));
        $main_categories = MainCategory::orderBy('main_category')->get();

        // to set default in search

        $date_from = date('1-m-Y');
        $date_to = date('t-m-Y');
        return view('category::admin.index',
            compact('categories','date_from','date_to','main_categories')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('category::admin.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {

        $rules = [
            'main_category_id'=>'required',
            'category_name'=>'required|unique:categories,category_name'
        ];
        $request->validate($rules);

        $category = new Category;
        $category->main_category_id = $request->main_category_id;
        $category->category_name = $request->category_name;
        $category->slug = $request->category_name;

        if($request->is_featured){
            $category->is_featured = $request->is_featured;
        }

        if($request->hasFile('photo')){
            $file = $request->file('photo');
            $photo = time().'.'.$file->getClientOriginalExtension();
            $destination_path = public_path('/uploads');
            $file->move($destination_path,$photo);

            $category->photo = $photo;
        }
        $category->save();
        return back();
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('category::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $category = Category::where('slug',$id)->first();
        $main_categories = MainCategory::orderBy('main_category')->get();
            return view('category::admin.edit',
            compact('category','main_categories')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request,$id)
    {
        //
        $category = Category::where('slug',$id)->first();

        $rules = [
            'category_name'=>'required|unique:categories,category_name,'.$category->id
        ];

        $request->validate($rules);

        $category->category_name = $request->category_name;

        $category->main_category_id = $request->main_category_id;

        $category->slug = $request->category_name;

        if($request->is_featured){
            $category->is_featured = $request->is_featured;
        }else{
            $category->is_featured = '0';

        }



        if($request->hasFile('photo')){

            //remove file from the folder

            $old_file = public_path('/uploads').'/'.$category->photo;

            if(File::exists($old_file)){
                File::delete($old_file);
            }

            //upload new one
            $file = $request->file('photo');
            $photo = time().'.'.$file->getClientOriginalExtension();
            $destination_path = public_path('/uploads');
            $file->move($destination_path,$photo);

            $category->photo = $photo;
        }

        $category->save();

        return redirect()->route('category.index');
    }

    // delete

    public function delete(Request $request)
    {

        if ($request->slug) {
            $subcategory = Category::whereIn('slug', $request->slug)->delete();
        }

        return back();
    }


    // Ajax function for filtering

    public function search(Request $request){
        $keyword = $request->keyword;
        $date_from = date('Y-m-d',strtotime($request->date_from)) ;
        $date_to = date('Y-m-d',strtotime($request->date_to));
        $categories = Category::where('category_name', 'like', '%' .$keyword . '%')
                        ->whereBetween('created_at', [$date_from, $date_to])
                        ->get();
        return response()->json($categories);

    }
}

Modules/Category/Resources/views/admin/edit.blade.php
@extends('layouts.admin.main')
@section('title')
Edit Category
@endsection
@section('content')
<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Edit Category</h2>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <ul class="nav nav-tabs">
                        <li class="nav-item"><a class="nav-link active show" data-toggle="tab" href="#addUser">
                                Edit Category</a>
                        </li>
                    </ul>
                    <div class="tab-content mt-0">
                        <div class="tab-pane  active show" id="addUser">
                            <div class="body mt-2">
                                <form action="{{route('category.update',$category->slug)}}" method="post"
                                    enctype="multipart/form-data">
                                    @csrf
                                    <input name="_method" type="hidden" value="PUT">

                                    <div class="row clearfix">

                                        {{-- Main category --}}
                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text">Main Category</span>
                                                    </div>
                                                    <select name="main_category_id" id="" class="form-control">
                                                        <option value="">--Select Main Category--</option>
                                                        @foreach ($main_categories as $value)
                                                            <option value="{{ $value->id }}"
                                                                {{ old('main_category_id',$category->main_category_id) == $value->id ? 'selected' : '' }}
                                                            >{{ $value->main_category }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        {{-- Category Name --}}
                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text">Category</span>
                                                    </div>
                                                    <input type="text" name="category_name" class="form-control"
                                                        placeholder="Category Name *"
                                                        value="{{old('category_name',$category->category_name)}}"
                                                        required="">
                                                </div>
                                            </div>
                                        </div>

                                          {{-- is featured --}}

                                          <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label class="fancy-checkbox">
                                                    <input class="checkbox-tick" type="checkbox"
                                                        name="is_featured"
                                                         @if($category->is_featured==1) checked @endif
                                                          value="1">
                                                    <span>Is Featured?</span>
                                                </label>

                                            </div>
                                        </div>

                                        {{-- photo upload --}}

                                        <div class="col-12">


                                            <img src="{{ asset('public/uploads/'.$category->photo) }}" height="100"
                                                alt="Image">
                                            <div class="form-group mt-3 mb-5">
                                                <input type="file" name="photo" class="dropify">
                                                <small id="fileHelp" class="form-text text-muted">This is some
                                                    placeholder block-level help text for the above input. It's a bit
                                                    lighter and easily wraps to a new line.</small>
                                            </div>
                                        </div>


                                        <!-- hidden id -->

                                        <input type="hidden" name="id" value="{{$category->id}}">

                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary">Update</button>

                                            <a class="btn btn-secondary" href="{{url('category/categories')}}">
                                                CLOSE</a>
                                        </div>
                                    </div>
                                    @if($errors->any())
                                    {!! implode('', $errors->all("<div class='error'>
                                        <p style='color:red'>:message</p>
                                    </div>")) !!}
                                    @endif
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Modules/Category/Resources/views/admin/index.blade.php
@extends('layouts.admin.main')




@section('title')
Categories
@endsection
@section('content')

<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Categories
                    </h2>
                </div>
            </div>
        </div>

        <div class="row clearfix">

            <div class="col-lg-12">
                <div class="card">
                    <ul class="nav nav-tabs">
                        <li class="nav-item"><a class="nav-link @if(!session()->get('errors')) active show @endif"
                                data-toggle="tab" href="#Users"> Categories
                            </a></li>
                            @if(in_array('category.store',session('permission')))

                        <li class="nav-item"><a class="nav-link @if(session()->get('errors')) active show @endif"
                                data-toggle="tab" href="#addUser">Add New Category
                            </a></li>
                            @endif
                    </ul>
                    <div class="tab-content mt-0">
                        <div class="tab-pane @if(!session()->get('errors')) active show @endif" id="Users">
                             <!-- search -->

            @include('category::admin.search')
                            <div class="table-responsive">

                                <form method="post">
                                    @csrf
                                    @if(in_array('category.delete',session('permission')))

                                    <button class="btn btn-danger"
                                        onclick="return confirm('Do you really want to delete this item?')"
                                        formaction="{{ route('category.delete') }}" type="submit">
                                        <i class="fa fa-trash"></i>
                                    </button>

                                    @endif
                                    <table class="table table-hover table-custom spacing8"
                                    id="table-category">
                                        <thead>
                                            <tr>
                                                @if(in_array('category.delete',session('permission')))

                                                <th>
                                                    <label class="fancy-checkbox">
                                                        <input class="checkbox-tick" type="checkbox" id="check_all">
                                                        <span>#</span>
                                                    </label>
                                                </th>
                                                @endif
                                                <th>Category</th>

                                                @if(in_array('category.edit',session('permission')))

                                                    <th>Actions</th>
                                                @endif
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach ($categories as $value)

                                            <tr>
                                                @if(in_array('category.delete',session('permission')))

                                                    <td>

                                                        <label class="fancy-checkbox">
                                                            <input class="checkbox-tick checkitem" type="checkbox"
                                                                name="slug[]" value="{{ $value->slug }}">
                                                            <span></span>
                                                        </label>
                                                    </td>
                                                @endif

                                                <td>
                                                    <h6 class="mb-0"> {{$value->category_name}}</h6>
                                                </td>

                                                @if(in_array('category.edit',session('permission')))


                                                    <td>
                                                        <a href="{{route('category.edit',$value->slug)}}">
                                                            <i class="icon-pencil"></i>
                                                        </a>

                                                    </td>

                                                @endif

                                                @endforeach
                                        </tbody>
                                    </table>
                                </form>
                                {{-- {!! $categories->render() !!} --}}

                            </div>
                        </div>

                        @if(in_array('category.store',session('permission')))

                        <div class="tab-pane @if(session()->get('errors')) active show @endif" id="addUser">
                            <div class="body mt-2">

                                {{-- @include('expensecategory::common.create') --}}

                                <form action="{{route('category.store')}}" enctype="multipart/form-data" method="post">
                                    @csrf
                                    <div class="row clearfix">


                                        {{-- Main Category --}}

                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text">Main Category</span>
                                                    </div>
                                                    <select name="main_category_id" id="" class="form-control">
                                                        <option value="">--Select Main Category--</option>
                                                        @foreach ($main_categories as $value)
                                                            <option value="{{ $value->id }}"
                                                                {{ old('main_category_id') == $value->id ? 'selected' : '' }}
                                                            >{{ $value->main_category }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        {{-- Category --}}

                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">


                                                        <label for="category_name" class="input-group-text">Category</label>
                                                    </div>
                                                    <input type="text" name="category_name" id="category_name"
                                                        class="form-control show-tick @error('category_name') is-invalid @enderror"
                                                        placeholder="Category *" value="{{old('category_name')}}"
                                                        required="">
                                                </div>
                                            </div>
                                        </div>

                                        @error('category_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror


                                        {{-- is featured --}}

                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label class="fancy-checkbox">
                                                    <input class="checkbox-tick" type="checkbox"
                                                        name="is_featured" value="1">
                                                    <span>Is Featured?</span>
                                                </label>

                                            </div>
                                        </div>


                                        {{-- photo upload --}}

                                        <div class="col-12">
                                            <div class="form-group mt-3 mb-5">
                                                <input type="file" name="photo" class="dropify">
                                                <small id="fileHelp" class="form-text text-muted">This is some
                                                    placeholder block-level help text for the above input. It's a bit
                                                    lighter and easily wraps to a new line.</small>
                                            </div>
                                        </div>


                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary">Add</button>
                                            <a class="btn btn-secondary"
                                                href="{{url('expensecategory/expensecategories')}}">
                                                CLOSE
                                            </a>
                                        </div>

                                    </div>

                                    @if($errors->any())
                                    {!! implode('', $errors->all("<div class='error'>
                                        <p style='color:red'>:message</p>
                                    </div>")) !!}
                                    @endif
                                </form>



                            </div>
                        </div>

                        @endif
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>




@endsection

Modules/Category/Resources/views/admin/search.blade.php
<form data-route="{{ route('category.search') }}" id="category-form">

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <input type="text" class="form-control category-keyword" placeholder="Search ..." name="keyword">
            </div>

        </div>

        <div class="col-md-3">
            <div class="form-group">
                <input type="text" value="{{ $date_from }}" data-provide="datepicker" readonly class="form-control date_from_category datepicker" placeholder="Date From " name="date_from" >
            </div>
        </div>

        <div class="col-md-3">

            <div class="form-group">
                <input type="text" value="{{ $date_to }}" data-provide="datepicker" readonly class="form-control date_to_category category-keyword datepicker" placeholder="Date To" name="date_to">
            </div>
        </div>
    </div>




</form>

Modules/Category/Resources/views/frontend/index.blade.php
@extends('layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('category.name') !!}
    </p>
@endsection