Modules/MainCategory/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('maincategory')->group(function() {
    Route::resource('maincategory','MainCategoryController');

    Route::post('maincategory/delete','MainCategoryController@delete')->name('maincategory.delete');
    Route::get('search','MainCategoryController@search')->name('maincategory.search');

});

Modules/MainCategory/Entities/MainCategory.php
<?php

namespace Modules\MainCategory\Entities;

use Illuminate\Database\Eloquent\Model;

class MainCategory extends Model
{
    protected $fillable = [];
}

Modules/MainCategory/Http/Controllers/MainCategoryController.php
<?php

namespace Modules\MainCategory\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\MainCategory\Entities\MainCategory;
use File;

class MainCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $main_categories = MainCategory::orderBy('main_category')->get();
        return view(
            'maincategory::admin.index',
            compact('main_categories')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('maincategory::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        $rules = [
            'main_category' => 'required|unique:main_categories,main_category'
        ];

        $request->validate($rules);

        $main_category = new MainCategory();
        $main_category->main_category = $request->main_category;
        $main_category->slug = date('ymdhis') . rand(0, 9999);

        if ($request->hasFile('photo')) {
            //upload new one
            $file = $request->file('photo');
            $photo = time() . '.' . $file->getClientOriginalExtension();
            $destination_path = public_path('/uploads');
            $file->move($destination_path, $photo);

            $main_category->photo = $photo;
        }
        $main_category->save();

        return back();
    }

  

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $main_category = MainCategory::where('slug',$id)->first();
        return view('maincategory::admin.edit',compact('main_category'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {

        $main_category = MainCategory::where('slug',$id)->first();


        $id = $main_category->id;

        $rules = [
            'main_category' => 'required|unique:main_categories,main_category,' . $id
        ];

        $request->validate($rules);

        $main_category->main_category = $request->main_category;

        if($request->featured){
            $main_category->featured = $request->featured;
        }else{
            $main_category->featured = '0';

        }
        // $main_category->slug = date('ymdhis').rand(0,9999);

        if ($request->hasFile('photo')) {

            //remove file from the folder

            $old_file = public_path('/uploads') . '/' . $category->photo;

            if (File::exists($old_file)) {
                File::delete($old_file);
            }

            //upload new one
            $file = $request->file('photo');
            $photo = time() . '.' . $file->getClientOriginalExtension();
            $destination_path = public_path('/uploads');
            $file->move($destination_path, $photo);

            $main_category->photo = $photo;
        }
        $main_category->save();

        return redirect()->route('maincategory.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function delete(Request $request)
    {
        if ($request->slug) {
            $main_categories = MainCategory::whereIn('slug', $request->slug)

                ->get();

            foreach ($main_categories as $value) {
                $old_file = public_path('/uploads') . '/' . $value->photo;

                if (File::exists($old_file)) {
                    File::delete($old_file);
                }

                $value->delete();
            }
        }

        return back();
    }


    //search

    public function search(Request $request){

        $date_from = $request->date_from;
        $date_to = $request->date_to;
        $keyword = $request->keyword;

        $main_categories = MainCategory::where('main_category', 'like', '%' .$keyword . '%');

        if($request->date_from && $request->date_to){

            $date_from = date('Y-m-d',strtotime($date_from));
            $date_to = date('Y-m-d',strtotime($date_to));
        }

        $main_categories = $main_categories->orderBy('main_category')->get();

        return response()->json($main_categories);
    }
}

Modules/MainCategory/Resources/views/admin/create.blade.php
<form action="{{route('maincategory.store')}}" enctype="multipart/form-data" method="post">
    @csrf
    <div class="row clearfix">

        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">


                        <label for="maincategory_name" class="input-group-text">maincategory</label>
                    </div>
                    <input type="text" name="main_category" id="maincategory_name"
                        class="form-control show-tick @error('main_category') is-invalid @enderror"
                        placeholder="maincategory *" value="{{old('main_category')}}"
                        required="">
                </div>
            </div>
        </div>

        @error('main_category')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror


        {{-- is featured --}}

        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="form-group">
                <label class="fancy-checkbox">
                    <input class="checkbox-tick" type="checkbox"
                        name="featured" value="1">
                    <span>Is Featured?</span>
                </label>

            </div>
        </div>


        {{-- photo upload --}}

        <div class="col-12">
            <div class="form-group mt-3 mb-5">
                <input type="file" name="photo" class="dropify">
                <small id="fileHelp" class="form-text text-muted">
            </div>
        </div>


        <div class="col-12">
            <button type="submit" class="btn btn-primary">Add</button>
            <a class="btn btn-secondary"
                href="{{route('maincategory.index')}}">
                CLOSE
            </a>
        </div>

    </div>

    @if($errors->any())
    {!! implode('', $errors->all("<div class='error'>
        <p style='color:red'>:message</p>
    </div>")) !!}
    @endif
</form>

Modules/MainCategory/Resources/views/admin/edit.blade.php
@extends('layouts.admin.main')
@section('title')
Edit Category
@endsection
@section('content')
<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Edit Main Category</h2>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <ul class="nav nav-tabs">
                        <li class="nav-item"><a class="nav-link active show" data-toggle="tab" href="#addUser">
                                Edit Main Category</a>
                        </li>
                    </ul>
                    <div class="tab-content mt-0">
                        <div class="tab-pane  active show" id="addUser">
                            <div class="body mt-2">
                                <form action="{{route('maincategory.update',$main_category->slug)}}" method="post"
                                    enctype="multipart/form-data">
                                    @csrf
                                    <input name="_method" type="hidden" value="PUT">

                                    <div class="row clearfix">
                                        <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text">Category</span>
                                                    </div>
                                                    <input type="text" name="main_category" class="form-control"
                                                        placeholder="Category Name *"
                                                        value="{{old('main_category',$main_category->main_category)}}"
                                                        required="">
                                                </div>
                                            </div>
                                        </div>

                                          {{-- is featured --}}

                                          <div class="col-lg-6 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label class="fancy-checkbox">
                                                    <input class="checkbox-tick" type="checkbox"
                                                        name="featured"
                                                         @if($main_category->featured==1) checked @endif
                                                          value="1">
                                                    <span>Is Featured?</span>
                                                </label>

                                            </div>
                                        </div>

                                        {{-- photo upload --}}

                                        <div class="col-12">


                                            <img src="{{ asset('public/uploads/'.$main_category->photo) }}" height="100"
                                                alt="Image">
                                            <div class="form-group mt-3 mb-5">
                                                <input type="file" name="photo" class="dropify">

                                            </div>
                                        </div>


                                        <!-- hidden id -->

                                        <input type="hidden" name="id" value="{{$main_category->id}}">

                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary">Update</button>

                                            <a class="btn btn-secondary" href="{{route('maincategory.index')}}">
                                                CLOSE</a>
                                        </div>
                                    </div>
                                    @if($errors->any())
                                    {!! implode('', $errors->all("<div class='error'>
                                        <p style='color:red'>:message</p>
                                    </div>")) !!}
                                    @endif
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Modules/MainCategory/Resources/views/admin/index.blade.php
@extends('layouts.admin.main')




@section('title')
Main Categories
@endsection
@section('content')

<div id="main-content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Main Categories
                    </h2>
                </div>
            </div>
        </div>

        <div class="row clearfix">

            <div class="col-lg-12">
                <div class="card">
                    <ul class="nav nav-tabs">
                        <li class="nav-item"><a class="nav-link @if(!session()->get('errors')) active show @endif"
                                data-toggle="tab" href="#Users"> Main Categories
                            </a></li>
                            @if(in_array('maincategory.store',session('permission')))

                        <li class="nav-item"><a class="nav-link @if(session()->get('errors')) active show @endif"
                                data-toggle="tab" href="#addUser">Add New maincategory
                            </a></li>
                            @endif
                    </ul>
                    <div class="tab-content mt-0">
                        <div class="tab-pane @if(!session()->get('errors')) active show @endif" id="Users">
                             <!-- search -->

            @include('maincategory::admin.search')
                            <div class="table-responsive">

                                <form method="post">
                                    @csrf
                                    @if(in_array('maincategory.delete',session('permission')))

                                    <button class="btn btn-danger"
                                        onclick="return confirm('Do you really want to delete this item?')"
                                        formaction="{{ route('maincategory.delete') }}" type="submit">
                                        <i class="fa fa-trash"></i>
                                    </button>

                                    @endif
                                    <table class="table table-hover table-custom spacing8"
                                    id="table-maincategory">
                                        <thead>
                                            <tr>
                                                @if(in_array('maincategory.delete',session('permission')))

                                                <th>
                                                    <label class="fancy-checkbox">
                                                        <input class="checkbox-tick" type="checkbox" id="check_all">
                                                        <span>#</span>
                                                    </label>
                                                </th>
                                                @endif
                                                <th>Main Category</th>

                                                @if(in_array('maincategory.edit',session('permission')))

                                                    <th>Actions</th>
                                                @endif
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach ($main_categories as $value)

                                            <tr>
                                                @if(in_array('maincategory.delete',session('permission')))

                                                    <td>

                                                        <label class="fancy-checkbox">
                                                            <input class="checkbox-tick checkitem" type="checkbox"
                                                                name="slug[]" value="{{ $value->slug }}">
                                                            <span></span>
                                                        </label>
                                                    </td>
                                                @endif

                                                <td>
                                                    <h6 class="mb-0"> {{$value->main_category}}</h6>
                                                </td>

                                                @if(in_array('maincategory.edit',session('permission')))


                                                    <td>
                                                        <a href="{{route('maincategory.edit',$value->slug)}}">
                                                            <i class="icon-pencil"></i>
                                                        </a>

                                                    </td>

                                                @endif

                                                @endforeach
                                        </tbody>
                                    </table>
                                </form>
                                {{-- {!! $Main Categories->render() !!} --}}

                            </div>
                        </div>

                        @if(in_array('maincategory.store',session('permission')))

                            <div class="tab-pane @if(session()->get('errors')) active show @endif" id="addUser">
                                <div class="body mt-2">

                                    @include('maincategory::admin.create')
                                </div>
                            </div>

                        @endif
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>




@endsection

Modules/MainCategory/Resources/views/admin/search.blade.php
<form data-route="{{ route('maincategory.search') }}" id="main-category-form">

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <input type="text" class="form-control main-category-keyword" placeholder="Search ..." name="keyword">
            </div>

        </div>

        <div class="col-md-3">
            <div class="form-group">
                <input type="text" value="{{ @$date_from }}" data-provide="datepicker" readonly class="form-control date_from_category datepicker" placeholder="Date From " name="date_from" >
            </div>
        </div>

        <div class="col-md-3">

            <div class="form-group">
                <input type="text" value="{{ @$date_to }}" data-provide="datepicker" readonly class="form-control date_to_category category-keyword datepicker" placeholder="Date To" name="date_to">
            </div>
        </div>
    </div>

</form>